import type { Metadata } from "next";
import "./globals.css";
import Header from "./ui/components/header";
import LeftNav from "./ui/components/leftnav";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: {
        template: "%s | MyApp",
        default: "MyApp"
    },
    description: "Generated by create next app"
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className="text-light-100 bg-dark-200 grid">
                <Suspense>
                {children}
                </Suspense>
            </body>
        </html>
    );
}

{/* <div className="w-32 h-8 bg-dark-100"></div>
<div className="w-32 h-8 bg-dark-200"></div>
<div className="w-32 h-8 bg-dark-300"></div>
<div className="w-32 h-8 bg-light-100"></div>
<div className="w-32 h-8 bg-light-200"></div>
<div className="w-32 h-8 bg-light-300"></div>
<div className="w-32 h-8 bg-primary-100"></div>
<div className="w-32 h-8 bg-primary-200"></div>
<div className="w-32 h-8 bg-primary-300"></div>
<div className="w-32 h-8 bg-primary-600"></div>
<div className="w-32 h-8 bg-primary-900"></div>
<div className="w-32 h-8 bg-accent-400"></div>
<div className="w-32 h-8 bg-accent-600"></div> */}